import { registerEnumType } from '@nestjs/graphql';

export const REPUTATION_VALUES = {
  QUESTION_VOTED_UP: 10,
  ANSWER_VOTED_UP: 10,
  ANSWER_ACCEPTED: 10,
  ANSWER_ACCETOR: 2,
  QUESTION_VOTE_DOWN: -2,
  ANSWER_VOTE_DOWN: -2,
  YOU_VOTE_DOWN_ANSWER: -1,
};

export enum REPUTATION_TYPES {
  QUESTION_VOTED_UP = 'QUESTION_VOTED_UP',
  ANSWER_VOTED_UP = 'ANSWER_VOTED_UP',
  ANSWER_ACCEPTED = 'ANSWER_ACCEPTED',
  ANSWER_ACCETOR = 'ANSWER_ACCETOR',
  QUESTION_VOTE_DOWN = 'QUESTION_VOTE_DOWN',
  ANSWER_VOTE_DOWN = 'ANSWER_VOTE_DOWN',
  YOU_VOTE_DOWN_ANSWER = 'YOU_VOTE_DOWN_ANSWER',
}

registerEnumType(REPUTATION_TYPES, {
  name: 'REPUTATION_TYPES',
});

export const MAX_DAILY_REPUTATION = 200;

export const NEW_USER_REPUTATION = 1;
