export const REPUTATION_VALUES = {
  QUESTION_VOTED_UP: 10,
  ANSWER_VOTED_UP: 10,
  ANSWER_ACCEPTED: 2,
  QUESTION_VOTE_DOWN: -2,
  ANSWER_VOTE_DOWN: -2,
  YOU_VOTE_DOWN_ANSWER: -1,
};

export const MAX_DAILY_REPUTATION = 200;
